In [2]:
import jieba
import jieba.posseg as pseg
import jieba.analyse
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
#jieba.set_dictionary('dict.txt.big')
jieba.set_dictionary('dict.txt.big.txt')

j=1
path='C:\\Users\\amos\\Desktop\\PTTwebcrawler\\mobile\\'
#path='C:\\Users\\User\\Desktop\\PTTwebcrawler\\mobile\\'
list_food=[]

#print(list_food)
for i in range (1,101):
    f = open(path+'m_'+str(j)+'.text','r',encoding = 'utf8')
    #content=f.readlines()
    content=f.read()
    eachdoc_cut=jieba.cut(content,cut_all=False)
    eachdoc_str=''
    for k in eachdoc_cut:
        #print(k)
        eachdoc_str=eachdoc_str+k+' '
    
    eachdoc_str=eachdoc_str.strip()
    list_food.append(eachdoc_str)

    f.close()
    j=j+1
# for q in range (0,2):
#     print(list_food[q])



Building prefix dict from C:\Users\amos\Desktop\PTTwebcrawler\dict.txt.big.txt ...
Loading model from cache C:\Users\amos\AppData\Local\Temp\jieba.u1ad717f44f295317eaab682294acefca.cache
Loading model cost 1.371 seconds.
Prefix dict has been built succesfully.


In [3]:
print(len(list_food))

100


In [4]:
tfidf_matrix_toarray=[]
tfidf_matrix_array=[]
list_feature=[]
feature_counter=0
#analyzer=lambda x:x.split(' ')
tfidfVecorizer = TfidfVectorizer()
tfidf_matrix = tfidfVecorizer.fit_transform(list_food)
tfidf_matrix_toarray=tfidf_matrix.toarray()
# print(tfidf_matrix[78,0])
# print('---------')

c=0
for a in range(0,len(tfidf_matrix.toarray())):
    for b in range(0,len(tfidf_matrix.toarray()[0])):
        tfidf_matrix_array.append(tfidf_matrix_toarray[a][b])
        c=c+1
tfidf_matrix_array.sort(reverse = True)

for aa in range (0,60):
    print(tfidf_matrix_array[aa])

term2id_dict = tfidfVecorizer.vocabulary_
new_dict = {v : k for k, v in term2id_dict.items()}

#print(len(new_dict))
#print(tfidf_matrix[10,12])

0.8803718712736968
0.7423260208075497
0.7353639599331502
0.7188415817691746
0.6125913195307152
0.5880907494818336
0.5803293332740785
0.5753554958519685
0.5647086732328789
0.5620584832553043
0.5606814812590379
0.5529501890649909
0.5420009619043332
0.5394270688948948
0.5388463949054464
0.5370854917541675
0.5313249303710693
0.5266185275987441
0.5222943090165681
0.5184845555508811
0.5035102052499654
0.5029639086987182
0.4948704434778695
0.49347171742097373
0.49267673341695634
0.49244332876699837
0.4882055657712182
0.4858518708526326
0.4804239222424808
0.4772268532969237
0.4761507135657142
0.47201993901034706
0.4713849637354045
0.4649324619413176
0.46271994939652344
0.4625963260889306
0.45937338620416995
0.4591149246806859
0.45054618105704103
0.4504130484405088
0.44763909629920184
0.4469445569414774
0.44551529386399524
0.444540258151118
0.4443051438625474
0.44156640121502944
0.4338866743363821
0.433352528268335
0.43259036712627236
0.4324464366842597
0.4292758378916088
0.42506383659164787
0.

In [5]:

Max_60words_food=[]
for i in range(0,60):
    maxx = np.where(tfidf_matrix_toarray==np.max(tfidf_matrix_toarray))
    print(maxx)
    #print(wordOfMobile[maxx[1][0]] , tfidf_matrix[maxx[0][0],maxx[1][0]])
    Max_60words_food.append(maxx[1][0])
    print(tfidf_matrix_toarray[maxx[0][0]][maxx[1][0]])
    #tfidf_matrix_toarray[maxx[0][0]][maxx[1][0]]=0
    for jj in range(0,100):
        tfidf_matrix_toarray[jj][maxx[1][0]] = 0

print(len(Max_60words_food)) 
print(Max_60words_food) 



# f = open(path+'f_0'+'.text','w',encoding = 'utf8')
# f.write(tags)
# f.close()
#print('\n'.join(tags))
#print(list_feature)

(array([99], dtype=int32), array([1109], dtype=int32))
0.8803718712736968
(array([71], dtype=int32), array([4454], dtype=int32))
0.7423260208075497
(array([60], dtype=int32), array([6278], dtype=int32))
0.7353639599331502
(array([58], dtype=int32), array([9071], dtype=int32))
0.7188415817691746
(array([38], dtype=int32), array([1787], dtype=int32))
0.6125913195307152
(array([89], dtype=int32), array([8418], dtype=int32))
0.5880907494818336
(array([19], dtype=int32), array([9326], dtype=int32))
0.5803293332740785
(array([11], dtype=int32), array([898], dtype=int32))
0.5753554958519685
(array([70], dtype=int32), array([6671], dtype=int32))
0.5647086732328789
(array([54], dtype=int32), array([10], dtype=int32))
0.5620584832553043
(array([41], dtype=int32), array([7231], dtype=int32))
0.5606814812590379
(array([96], dtype=int32), array([8], dtype=int32))
0.5529501890649909
(array([39], dtype=int32), array([7795], dtype=int32))
0.5420009619043332
(array([78], dtype=int32), array([2248], dty

In [9]:
tags=''
list_tags=[]
for sixty in range(0,60):
    print(new_dict[Max_60words_food[sixty]])
    list_tags.append(new_dict[Max_60words_food[sixty]])
tags=",".join(str(i) for i in list_tags)
print(tags)
print(len(list_tags))

f = open(path+'m_0'+'.text','w',encoding = 'utf8')
f.write(tags)
f.close()

done
同步
晴空
雙清
larsonloreal
越南
鬧鐘
bwhmj
殘影
04
白邊
03
耳塞
ping
08
通知
藍芽
資料夾
耳道
切換
m9
iphone
感應
安全
那條
05
u11
hdr
andyfresh
自拍
備份
日本
f7
qday
平板
降價
聊天
yurian
oled
印度
g5
188
山寨
sense
mate
xp
angela60531
joshua781021
簡訊
黑卡
原生
流量
視訊
sugar
皮套
kkcity59
相簿
zenui
tony12526
待機
done,同步,晴空,雙清,larsonloreal,越南,鬧鐘,bwhmj,殘影,04,白邊,03,耳塞,ping,08,通知,藍芽,資料夾,耳道,切換,m9,iphone,感應,安全,那條,05,u11,hdr,andyfresh,自拍,備份,日本,f7,qday,平板,降價,聊天,yurian,oled,印度,g5,188,山寨,sense,mate,xp,angela60531,joshua781021,簡訊,黑卡,原生,流量,視訊,sugar,皮套,kkcity59,相簿,zenui,tony12526,待機
60
