In [1]:
import jieba
import jieba.posseg as pseg
import jieba.analyse
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
#jieba.set_dictionary('dict.txt.big')
jieba.set_dictionary('dict.txt.big.txt')

j=1
#path='C:\\Users\\amos\\Desktop\\PTTwebcrawler\\food\\'
path='C:\\Users\\User\\Desktop\\PTTwebcrawler\\mobile\\'
list_food=[]
eachdoc_str=''
#print(list_food)
for i in range (1,101):
    f = open(path+'m_'+str(j)+'.text','r',encoding = 'utf8')
    #content=f.readlines()
    content=f.read()
    eachdoc_cut=jieba.cut(content,cut_all=False)
    
    for k in eachdoc_cut:
        #print(k)
        eachdoc_str=eachdoc_str+k+' '
    
    eachdoc_str=eachdoc_str.strip()
    list_food.append(eachdoc_str)

    f.close()
    j=j+1
# for q in range (0,2):
#     print(list_food[q])



Building prefix dict from C:\Users\User\Desktop\PTTwebcrawler\dict.txt.big.txt ...
Loading model from cache C:\Users\User\AppData\Local\Temp\jieba.ue632347d561f2f989c94bc7035543b52.cache
Loading model cost 1.397 seconds.
Prefix dict has been built succesfully.


In [2]:
print(len(list_food))

100


In [25]:
tfidf_matrix_toarray=[]
tfidf_matrix_array=[]
list_feature=[]
feature_counter=0
#analyzer=lambda x:x.split(' ')
tfidfVecorizer = TfidfVectorizer()
tfidf_matrix = tfidfVecorizer.fit_transform(list_food)
tfidf_matrix_toarray=tfidf_matrix.toarray()
# print(tfidf_matrix[78,0])
# print('---------')

c=0
for a in range(0,len(tfidf_matrix.toarray())):
    for b in range(0,len(tfidf_matrix.toarray()[0])):
        tfidf_matrix_array.append(tfidf_matrix_toarray[a][b])
        c=c+1
tfidf_matrix_array.sort(reverse = True)

for aa in range (0,60):
    print(tfidf_matrix_array[aa])

term2id_dict = tfidfVecorizer.vocabulary_
new_dict = {v : k for k, v in term2id_dict.items()}

#print(len(new_dict))
#print(tfidf_matrix[10,12])

0.7735071253724031
0.772191427670835
0.7721331074887852
0.7719076685049787
0.767484289114062
0.7666052436521792
0.766184311641439
0.7648970285933884
0.7642917358808942
0.7641741164147292
0.7641169765446314
0.7638823590640379
0.7638619272852504
0.7637787425459575
0.7628542817805611
0.7627341857125605
0.7614599945489248
0.7597967235989184
0.7597508887221456
0.759371407851805
0.7578420228002923
0.7575447833761673
0.755975915928144
0.7559089804145858
0.7544367928116134
0.7543865172318063
0.7539198250904157
0.7532633549720339
0.7531350281908796
0.7530620742756914
0.7529925850425627
0.7527959059073833
0.7527302700775271
0.7491926500144166
0.7488053765519194
0.7478373344846978
0.7472015984188264
0.7428327556625557
0.7414036370879237
0.7385249293319173
0.7365544390415325
0.7365304204761556
0.7356197559820596
0.7346200086319377
0.7330058567771385
0.7296343475633263
0.7239991727681572
0.7222922486894793
0.7222516928706462
0.72179402285143
0.7215595210108748
0.720880561281877
0.7198067434622353
0

In [26]:

Max_60words_food=[]
for i in range(0,60):
    maxx = np.where(tfidf_matrix_toarray==np.max(tfidf_matrix_toarray))
    print(maxx)
    #print(wordOfMobile[maxx[1][0]] , tfidf_matrix[maxx[0][0],maxx[1][0]])
    Max_60words_food.append(maxx[1][0])
    print(tfidf_matrix_toarray[maxx[0][0]][maxx[1][0]])
    #tfidf_matrix_toarray[maxx[0][0]][maxx[1][0]]=0
    for jj in range(0,100):
        tfidf_matrix_toarray[jj][maxx[1][0]] = 0

print(len(Max_60words_food)) 
print(Max_60words_food) 



# f = open(path+'f_0'+'.text','w',encoding = 'utf8')
# f.write(tags)
# f.close()
#print('\n'.join(tags))
#print(list_feature)

(array([99], dtype=int32), array([20], dtype=int32))
0.7735071253724031
(array([32], dtype=int32), array([15], dtype=int32))
0.5975743483567656
(array([91], dtype=int32), array([13], dtype=int32))
0.28272668364471915
(array([3], dtype=int32), array([243], dtype=int32))
0.25141012456519857
(array([0], dtype=int32), array([302], dtype=int32))
0.19386359088230085
(array([11], dtype=int32), array([16], dtype=int32))
0.18266198574683118
(array([13], dtype=int32), array([316], dtype=int32))
0.18121776774333348
(array([0], dtype=int32), array([4609], dtype=int32))
0.1661687921848293
(array([5], dtype=int32), array([5762], dtype=int32))
0.13398785851598732
(array([8], dtype=int32), array([276], dtype=int32))
0.12927224190583436
(array([0], dtype=int32), array([43], dtype=int32))
0.1292423939215339
(array([0], dtype=int32), array([326], dtype=int32))
0.12001079435571005
(array([19], dtype=int32), array([55], dtype=int32))
0.09878326249304659
(array([24], dtype=int32), array([67], dtype=int32))


In [27]:
tags=''
list_tags=[]
for sixty in range(0,60):
    print(new_dict[Max_60words_food[sixty]])
    list_tags.append(new_dict[Max_60words_food[sixty]])
tags=",".join(str(i) for i in list_tags)
print(tags)

f = open(path+'m_0'+'.text','w',encoding = 'utf8')
f.write(tags)
f.close()

08
05
04
19
21
06
22
問題
手機
20
11
23
12
13
ios
00
02
電池
可以
16
18
07
身弓
03
15
https
2018
解決
28
10
17
bwhmj
dfight
原廠
36
01
cc
更新
ptt
mobilecomm
ajizzinpants
果粉
14
遊戲
指紋
com
沒有
這個
09
45
真的
app
版本
使用
bug
heathclifff
hyghmax1202
不是
什麼
充電
08,05,04,19,21,06,22,問題,手機,20,11,23,12,13,ios,00,02,電池,可以,16,18,07,身弓,03,15,https,2018,解決,28,10,17,bwhmj,dfight,原廠,36,01,cc,更新,ptt,mobilecomm,ajizzinpants,果粉,14,遊戲,指紋,com,沒有,這個,09,45,真的,app,版本,使用,bug,heathclifff,hyghmax1202,不是,什麼,充電
